# jekyll config for pinktrace home page

# Configuration
markdown: maruku
permalink: "/:year/:month/:day/:title"
pygments: true
lsi: false
exclude: [ Makefile, Makefile.am, Makefile.in ]

# Custom variables
author: "Ali Polatel"
mail: "alip@exherbo.org"
uri: "http://alip.github.com/pinktrace/"
uri_scm: "git://github.com/alip/pinktrace.git"
uri_scm_view: "http://github.com/alip/pinktrace/"
uri_support: "http://github.com/alip/pinktrace/issues/"

# Let autoconf fill the rest in
version: "0.1.3"
title: "pinktrace-0.1.3"
